version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: eduvibe_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eduvibe
      MYSQL_USER: eduvibe_user
      MYSQL_PASSWORD: eduvibe_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: