# Usa una imagen de Node.js para construir la aplicación Angular
FROM node:20.12.2 as build
# Establece el directorio de trabajo
WORKDIR /app
# Copia el resto de los archivos del proyecto
COPY . .
# Instala las dependencias
RUN npm install
# Construye la aplicación Angular
RUN npm run build --prod
# Usa una imagen de Nginx para servir la aplicación Angular
FROM nginx:stable-alpine
LABEL author="Javier Pintado Navarro"
# Copia los archivos construidos desde la fase de construcción
COPY --from=build /app/browser /usr/share/nginx/html
# Copia la configuración de Nginx si es necesario
# COPY ./nginx.conf /etc/nginx/nginx.conf
# Exponer el puerto en el que Nginx servirá la aplicación
EXPOSE 80
# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
